name: 🚀 Deploy Allura to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: 🔄 SSH Deploy to Remote Server
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            git pull origin main
            docker compose down
            docker compose up -d --build
